version: "3"
services:
  #nginx:
    #image: nginx
    #ports:
      #- 80
        #volumes:
        #- "./nginx/nginx.conf:/etc/nginx/nginx.conf"
  rest:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - "./data:/data:rw"
