version: "3"
services:
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
  rest:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - "./data:/data:rw"
